### ISSUE TITLE
Move to cta-observatory?

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/protozfitsreader#63]
This project is used also for LST and other cameras.

Could we transfer this project to cta-observatory?

**Comment by Etienne12345** [comment]
Hello Max, 

Last that I heard, a decision was needed regarding DL0 format before moving the ZFITS reader to CTA repository (ie. if ZFITS is not chosen, it won't be moved). 

If the situation has changed, and if it makes sense to move this project, then ok with me (I only need write access to be able to update the binary layer in the future). 

Cheers !

**Comment by MaxNoe** [comment]
I don't see how a final decision on the DL0 format would affect a reader software for one of the proposed formats. Anything in that orga is currently a prototype.

Let's ask @kosack.

**Comment by kosack** [comment]
I think we can move it - even if it's not the official DL0, it's still useful now.

**Comment by MaxNoe** [comment]
I forked this repo to cta-observatory and added you as admin @Etienne12345.

If it's ok with all of you, I would propose to add a comment here that developement has moved to the cta-observatory repository and make new changes there.

**Comment by MaxNoe** [comment]
I did this, to preserve the release links that re currently used by many people

**Comment by dneise** [comment]
Hey guys, sorry to be late to the party. I am back for a couple of month now.
Until end of November to be precise.

Anyway, I guess we could have transfered ownership to cta-observatory, If I remember correctly, in case of an ownership transfer, github handles all the URL forwarding, so people still using the old URL are simply forwarded. 

Also repos, who are set up to use the old URLs will then be forwarded to the new location. I think that is superior to just writing a note here...

I am currently checking the github docs if that is still possible after the fact.
Otherwise, we could maybe for simplicity quickly delete `cta-observatory/protozfitsreader` and then transfer ownership?

**Comment by MaxNoe** [comment]
Ah right: 

> All links to the previous repository location are automatically redirected to the new location. 

I somehow thought this wouldn't  work for the releases

**Comment by dneise** [comment]
I quickly made Max an admin of this repo here. So one person can easily fix this issue on their own timescale. Is that fine for you max?

**Comment by MaxNoe** [comment]
I'm doing it now

**Comment by MaxNoe** [comment]
Should be done. You all should still have access.
